### ISSUE TITLE
Implement Multiples

### ISSUE THREAD

**Issue by CCalamos-ICF** [ccalamos/gatsby-source-googlemaps-static#7]
Add the option of multiples that can inherit from globals

**Comment by robinmetral** [comment]
@ccalamos by `multiples`, do you mean the option to source multiple maps?

Sourcing multiple maps is a requested feature from [this question](https://stackoverflow.com/questions/60894586/gatsby-source-google-maps-static-plugin/60898251) - would you consider looking into it? If this issue is about something different, we can open a new one.

Nice looking plugin by the way ✨

**Comment by ccalamos** [comment]
Hey @robinmetral yes that is what this enhancement is referencing. Since there is interest I will start development on it this week.

**Comment by robinmetral** [comment]
Thanks a lot for your quick update @ccalamos! Let me know if you need help 🙂

**Comment by ccalamos** [comment]
Pushed an update for multiples and updated the README
